import type {
  Device,
  Farmer,
  Farm,
  Assignment,
  SensorReading,
  Admin,
  DashboardStats,
} from "./types";

export const dummyDevices: Device[] = [
  {
    id: "DEV001",
    name: "Water Sensor Alpha",
    status: "active",
    farmId: "FARM001",
    farmName: "Green Valley Farm",
    lastActive: new Date("2025-10-15T10:30:00"),
    batteryLevel: 85,
  },
  {
    id: "DEV002",
    name: "Water Sensor Beta",
    status: "active",
    farmId: "FARM002",
    farmName: "Sunrise Fields",
    lastActive: new Date("2025-10-15T09:15:00"),
    batteryLevel: 92,
  },
  {
    id: "DEV003",
    name: "Water Sensor Gamma",
    status: "inactive",
    lastActive: new Date("2025-10-14T16:45:00"),
    batteryLevel: 12,
  },
  {
    id: "DEV004",
    name: "Water Sensor Delta",
    status: "maintenance",
    farmId: "FARM003",
    farmName: "Golden Harvest",
    lastActive: new Date("2025-10-13T14:20:00"),
    batteryLevel: 45,
  },
  {
    id: "DEV005",
    name: "Water Sensor Epsilon",
    status: "active",
    farmId: "FARM001",
    farmName: "Green Valley Farm",
    lastActive: new Date("2025-10-15T11:00:00"),
    batteryLevel: 78,
  },
];

export const dummyFarmers: Farmer[] = [
  {
    id: "FARMER001",
    name: "John Doe",
    email: "john.doe@email.com",
    phone: "+62 812-3456-7890",
    farmId: "FARM001",
    farmName: "Green Valley Farm",
    location: "Bandung, West Java",
    devicesActive: 2,
    createdAt: new Date("2025-01-15"),
  },
  {
    id: "FARMER002",
    name: "Jane Smith",
    email: "jane.smith@email.com",
    phone: "+62 813-9876-5432",
    farmId: "FARM002",
    farmName: "Sunrise Fields",
    location: "Yogyakarta, Central Java",
    devicesActive: 1,
    createdAt: new Date("2025-02-20"),
  },
  {
    id: "FARMER003",
    name: "Ahmad Ibrahim",
    email: "ahmad.ibrahim@email.com",
    phone: "+62 815-1111-2222",
    farmId: "FARM003",
    farmName: "Golden Harvest",
    location: "Malang, East Java",
    devicesActive: 1,
    createdAt: new Date("2025-03-10"),
  },
  {
    id: "FARMER004",
    name: "Siti Nurhaliza",
    email: "siti.nurhaliza@email.com",
    phone: "+62 816-3333-4444",
    farmId: "FARM004",
    farmName: "Rice Paradise",
    location: "Bogor, West Java",
    devicesActive: 0,
    createdAt: new Date("2025-04-05"),
  },
];

export const dummyFarms: Farm[] = [
  {
    id: "FARM001",
    name: "Green Valley Farm",
    location: "Bandung, West Java",
    farmerId: "FARMER001",
    farmerName: "John Doe",
    area: 5.2,
    devices: 2,
  },
  {
    id: "FARM002",
    name: "Sunrise Fields",
    location: "Yogyakarta, Central Java",
    farmerId: "FARMER002",
    farmerName: "Jane Smith",
    area: 3.8,
    devices: 1,
  },
  {
    id: "FARM003",
    name: "Golden Harvest",
    location: "Malang, East Java",
    farmerId: "FARMER003",
    farmerName: "Ahmad Ibrahim",
    area: 7.5,
    devices: 1,
  },
  {
    id: "FARM004",
    name: "Rice Paradise",
    location: "Bogor, West Java",
    farmerId: "FARMER004",
    farmerName: "Siti Nurhaliza",
    area: 4.2,
    devices: 0,
  },
];

export const dummyAssignments: Assignment[] = [
  {
    id: "ASSIGN001",
    deviceId: "DEV001",
    deviceName: "Water Sensor Alpha",
    farmerId: "FARMER001",
    farmerName: "John Doe",
    farmId: "FARM001",
    farmName: "Green Valley Farm",
    assignedAt: new Date("2025-09-01"),
    status: "active",
  },
  {
    id: "ASSIGN002",
    deviceId: "DEV002",
    deviceName: "Water Sensor Beta",
    farmerId: "FARMER002",
    farmerName: "Jane Smith",
    farmId: "FARM002",
    farmName: "Sunrise Fields",
    assignedAt: new Date("2025-09-15"),
    status: "active",
  },
  {
    id: "ASSIGN003",
    deviceId: "DEV004",
    deviceName: "Water Sensor Delta",
    farmerId: "FARMER003",
    farmerName: "Ahmad Ibrahim",
    farmId: "FARM003",
    farmName: "Golden Harvest",
    assignedAt: new Date("2025-10-01"),
    status: "inactive",
  },
  {
    id: "ASSIGN004",
    deviceId: "DEV005",
    deviceName: "Water Sensor Epsilon",
    farmerId: "FARMER001",
    farmerName: "John Doe",
    farmId: "FARM001",
    farmName: "Green Valley Farm",
    assignedAt: new Date("2025-10-10"),
    status: "active",
  },
];

export const dummySensorReadings: SensorReading[] = [
  {
    id: "READ001",
    deviceId: "DEV001",
    timestamp: new Date("2025-10-15T10:30:00"),
    ph: 7.2,
    temperature: 28.5,
    turbidity: 12.3,
    waterLevel: 85.5,
  },
  {
    id: "READ002",
    deviceId: "DEV001",
    timestamp: new Date("2025-10-15T09:30:00"),
    ph: 7.1,
    temperature: 27.8,
    turbidity: 13.1,
    waterLevel: 84.2,
  },
  {
    id: "READ003",
    deviceId: "DEV002",
    timestamp: new Date("2025-10-15T10:15:00"),
    ph: 6.9,
    temperature: 29.2,
    turbidity: 15.7,
    waterLevel: 78.3,
  },
  {
    id: "READ004",
    deviceId: "DEV001",
    timestamp: new Date("2025-10-15T08:30:00"),
    ph: 7.0,
    temperature: 26.5,
    turbidity: 14.2,
    waterLevel: 83.1,
  },
  {
    id: "READ005",
    deviceId: "DEV005",
    timestamp: new Date("2025-10-15T11:00:00"),
    ph: 7.3,
    temperature: 28.9,
    turbidity: 11.8,
    waterLevel: 86.7,
  },
];

export const dummyAdmins: Admin[] = [
  {
    id: "ADMIN001",
    username: "admin",
    email: "admin@kampungtani.com",
    role: "super admin",
    createdAt: new Date("2025-01-01"),
    lastLogin: new Date("2025-10-15T08:00:00"),
  },
  {
    id: "ADMIN002",
    username: "operator1",
    email: "operator1@kampungtani.com",
    role: "admin",
    createdAt: new Date("2025-03-15"),
    lastLogin: new Date("2025-10-14T16:30:00"),
  },
];

export const dummyDashboardStats: DashboardStats = {
  totalDevices: 5,
  activeDevices: 3,
  assignedDevices: 4,
  totalFarmers: 4,
  totalFarms: 4,
  todayReadings: 24,
};

// Chart data for sensor activity
export const sensorActivityData = [
  { date: "Oct 9", readings: 18 },
  { date: "Oct 10", readings: 22 },
  { date: "Oct 11", readings: 19 },
  { date: "Oct 12", readings: 25 },
  { date: "Oct 13", readings: 21 },
  { date: "Oct 14", readings: 23 },
  { date: "Oct 15", readings: 24 },
];
